test: added unit tests for invalid dump and version
mendersoftware/mender-snapshot pull request #25
Opened 2024-03-14 13:50 UTC by danielskinstad

Ticket: MEN-6897

2024-03-18 10:44 UTC, lluiscampos requested changes
Thank you. An small request to move the version tests to have more value. See below.

2024-03-18 10:44 UTC, lluiscampos commented on conf/version_test.go
> +}
These tests have very little value: we are setting a variable and then checking that it is returned.

Can we instead move it into the `cli_test.go` package and check that `mender-snapshot --version` prints the right thing? You can look at [mender-artifact cli tests](https://github.com/mendersoftware/mender-artifact/blob/master/cli/cli_test.go) for some inspiration

2024-03-18 10:44 UTC, lluiscampos commented on cli/cli_test.go
> +	assert.ErrorContains(t, err, "Refusing to write to terminal")
Nice test :sparkles:

2024-04-11 08:44 UTC, lluiscampos approved these changes

2024-04-11 09:30 UTC, danielskinstad commented
@mender-test-bot start pipeline

2024-04-11 13:29 UTC, merged